setwd("C:/Users/Adam/Desktop/Data Science Capstone/Assignment3/specdata")
getwd()

data1 <- read.csv("332.csv")
data2 <- read.csv("029.csv")
data3 <- read.csv("180.csv")

data1 <- na.omit(data1)
data2 <- na.omit(data2)
data3 <- na.omit(data3)

data1 <- (data1$nitrate)
	hist(data1)
	sulfD <- density(data1)
		
		par(mfrow=c(2,2))
			hist(data1, freq=F)
			lines(sulfD)
			boxplot(data1)
			qqnorm(data1)
			qqline(data1)
			barplot(data1)	
data2 <- (data2$nitrate)
	hist(data2)
	sulfD <- density(data2)
		
		par(mfrow=c(2,2))
			hist(data2, freq=F)
			lines(sulfD)
			boxplot(data2)
			qqnorm(data2)
			qqline(data2)
			barplot(data2)
data3 <- (data3$nitrate)
	hist(data3)
	sulfD <- density(data3)
		
		par(mfrow=c(2,2))
			hist(data3, freq=F)
			lines(sulfD)
			boxplot(data3)
			qqnorm(data3)
			qqline(data3)
			barplot(data3)